### PR TITLE
mtv-1143 updated attributes to 2.6.3

### PR DESCRIPTION
**Pull request by shdeshpa07**
## Jira 

* [MTV-1143](https://issues.redhat.com/browse/MTV-1143)

Updated z stream attributes to 2.6.3

### CODE REVIEW

**Comment by shdeshpa07** [comment]
@ahadas - Please could you review my attributes update.

**Comment by shdeshpa07** [comment]
@RichardHoch - Could you please review the attributes update ticket.

**Comment by RichardHoch** [comment]
LGTM

**Review by ahadas — APPROVED** [review]

**Comment by shdeshpa07** [comment]
@anarnold97 Arik has approved the change. Would you please merge the PR when you are ready? Thanks.

**Pull request merged**
