### PR TITLE
NFC-enabled vmkernel NIC migration option for MTV 2.5

### PR DESCRIPTION
**Pull request by RichardHoch**
MTV 2.5

Resolves https://issues.redhat.com/browse/MTV-1200 for MTV 2.5 by adding a note to the MTV UI and CLI migration procedures about configuring a host on the vmWare site, rather than via MTV.

Previews:

- https://file.emea.redhat.com/rhoch/mtv_1200_25/html-single/#adding-source-providers [see note in section 4.4.1.1.1, "Selecting a migration network for a VMware source provider"]
- https://file.emea.redhat.com/rhoch/mtv_1200_25/html-single/#new-migrating-virtual-machines-cli_vmware [see note at the end of step 3]

### CODE REVIEW

**Comment by fabiand** [comment]
@anarnold97 is this PR still relevant - or #538 ?

**Comment by anarnold97** [comment]
@RichardHoch - please can you confirm if i need to push this to MTV 2.5 docs? I know we merged and published 2.6

Thanks

**Comment by RichardHoch** [comment]
> @RichardHoch - please can you confirm if i need to push this to MTV 2.5 docs? I know we merged and published 2.6
> 
> If we need to merge, then please can you help me with the merge conflicts tomorrow
> 
> Thanks

This PR (537) needs merging into 2.5 -- but first -- this PR (511) needs merging in 2,5 (or the one line in it needs to added again to master.adoc in 2.5) https://github.com/kubev2v/forklift-documentation/pull/511

**Comment by RichardHoch** [comment]
@anarnold97  Closing this PR -- will open a new one that incorporates both these changes and those of PR 511 into a single fix for 2.5. 2.6 is OK as is.

**Pull request closed without merging**
